INSERT INTO boards(capacity, number, location) VALUES
(2, 1, 'AREA_INTERNA'),
(2, 2, 'AREA_INTERNA'),
(2, 3, 'AREA_INTERNA'),
(2, 4, 'AREA_INTERNA'),
(4, 5, 'AREA_INTERNA'),
(4, 6, 'AREA_INTERNA'),
(8, 7, 'AREA_INTERNA'),
(2, 8, 'AREA_INTERNA'),
(2, 9, 'AREA_INTERNA'),
(2, 10, 'AREA_EXTERNA_VARANDA'),
(2, 11, 'AREA_EXTERNA_VARANDA'),
(4, 12, 'AREA_EXTERNA_VARANDA');
